title = "Marcela"
baseurl = "http://www.marcelaviola.com"
[params]
  description = "Strength training, Mobility and Nutrition coaching."
  keywords = "coach, marcela, viola, health, wellness, coaching, personal, trainer, strength, mobility, flexibility, nutrition, training, fitness"

languagecode = "en_US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
relativeurls = false
canonifyurls = true
watch = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[author]
  name = "Natan Santolo"

[taxonomies]
  category = "categories"
  tag = "tags"

SectionPagesMenu = "main"

[[menu.main]]
  weight = 1
  name = "About"
  url = "#about"
[[menu.main]]
  weight = 2
  name = "Credentials"
  url = "#credentials"
[[menu.main]]
  weight = 3
  name = "Services"
  url = "#services"
[[menu.main]]
  weight = 4
  name = "Testimonials"
  url = "#testimonials"
[[menu.main]]
  weight = 5
  name = "Get in touch"
  url = "#contact"